insert into products (
  slug, name, brand, category, collection, colorway, price_cents, sale_price_cents,
  description_short, description_long, details, sizes, colors, tags, images,
  model_3d_url, has_3d, featured, active, stock, status
) values
(
  'air-jordan-4-white-gold',
  'Air Jordan 4 White Gold',
  'Jordan',
  'Tênis Masculino',
  'Edição Premium',
  'White / Black / Gold',
  149990,
  null,
  'Couro texturizado, detalhes dourados e visual de presença para quem quer um sneaker protagonista.',
  'Um modelo de alto impacto visual, pensado para compor a vitrine principal da HeMa Footwear. A construção combina painéis em branco, estrutura preta e detalhes dourados com acabamento premium.',
  '["Cabedal com textura premium", "Detalhes em dourado metálico", "Amortecimento confortável", "Visual ideal para destaque de vitrine"]'::jsonb,
  ARRAY['38','39','40','41','42','43','44'],
  ARRAY['White','Black','Gold'],
  ARRAY['premium','hero','jordan','dourado'],
  ARRAY['/assets/products/hero-branco-preto-dourado.png','/assets/products/dunk-preto-branco-dourado.png'],
  null,
  true,
  true,
  true,
  8,
  'published'
),
(
  'nike-dunk-low-retro-black-gold',
  'Nike Dunk Low Retro',
  'Nike',
  'Tênis Casual',
  'Lançamentos',
  'Black / White / Gold',
  79990,
  null,
  'Clássico urbano em preto, branco e dourado. Forte presença visual e fácil de combinar.',
  'O Dunk Low Retro é uma escolha certeira para quem procura um sneaker versátil, com leitura premium e presença suficiente para se destacar em looks casuais.',
  '["Silhueta clássica", "Colorway premium", "Confortável para uso diário", "Ótimo para looks streetwear"]'::jsonb,
  ARRAY['36','37','38','39','40','41','42','43'],
  ARRAY['Black','White','Gold'],
  ARRAY['nike','dunk','casual','best seller'],
  ARRAY['/assets/products/dunk-preto-branco-dourado.png'],
  null,
  false,
  true,
  true,
  12,
  'published'
),
(
  'adidas-samba-og-cloud-white',
  'Adidas Samba OG',
  'Adidas',
  'Tênis Casual',
  'Clássicos',
  'Cloud White / Core Black',
  69990,
  null,
  'Um clássico minimalista com sola gum e visual elegante para o dia a dia.',
  'O Samba OG traz estética retrô, perfil baixo e acabamento limpo. É um dos modelos mais fáceis de vender pela versatilidade e pelo apelo visual atemporal.',
  '["Perfil baixo", "Sola gum", "Combina com estilo casual", "Visual minimalista"]'::jsonb,
  ARRAY['34','35','36','37','38','39','40','41','42'],
  ARRAY['White','Black','Gum'],
  ARRAY['adidas','samba','clássico','minimalista'],
  ARRAY['/assets/products/samba-branco-preto.png'],
  null,
  false,
  true,
  true,
  15,
  'published'
),
(
  'jordan-4-retro-black-cat',
  'Jordan 4 Retro',
  'Jordan',
  'Tênis Masculino',
  'Essenciais',
  'Black Cat',
  149990,
  null,
  'All black, imponente e sofisticado. Um sneaker com presença forte.',
  'O Jordan 4 Black Cat é um produto de alto desejo, com leitura premium e apelo visual imediato. Ideal para compradores que preferem um visual discreto e marcante.',
  '["Construção monocromática", "Visual premium", "Alta presença", "Fácil de compor looks"]'::jsonb,
  ARRAY['38','39','40','41','42','43','44','45'],
  ARRAY['Black'],
  ARRAY['jordan','black cat','premium'],
  ARRAY['/assets/products/jordan4-preto.png'],
  null,
  false,
  true,
  true,
  6,
  'published'
),
(
  'nike-air-max-97-white-metallic-silver',
  'Nike Air Max 97',
  'Nike',
  'Tênis Lifestyle',
  'Lançamentos',
  'White / Metallic Silver',
  89990,
  79990,
  'Linhas futuristas, acabamento claro e presença elegante para qualquer vitrine.',
  'O Air Max 97 combina design inspirado em ondas com amortecimento aparente e acabamento premium. Um modelo excelente para páginas de detalhe com visualização 360º.',
  '["Amortecimento Air visível", "Design fluido e futurista", "Acabamento branco e prata", "Ótimo para visualização em detalhe"]'::jsonb,
  ARRAY['36','37','38','39','40','41','42','43','44'],
  ARRAY['White','Silver'],
  ARRAY['nike','air max','lifestyle','3d'],
  ARRAY['/assets/products/airmax97-branco-prata.png'],
  null,
  true,
  true,
  true,
  18,
  'published'
),
(
  'puma-rsx-reinvent-white-gold',
  'Puma RS-X Reinvent',
  'Puma',
  'Tênis Esportivo',
  'Lifestyle',
  'White / Gray / Gold',
  74990,
  null,
  'Chunky sneaker moderno com tons neutros e detalhes dourados.',
  'Modelo com visual volumoso, linhas técnicas e detalhes em ouro. Bom para clientes que buscam conforto e visual mais contemporâneo.',
  '["Solado robusto", "Visual moderno", "Detalhes dourados", "Boa presença em fotos"]'::jsonb,
  ARRAY['37','38','39','40','41','42','43'],
  ARRAY['White','Gray','Gold'],
  ARRAY['puma','chunky','moderno'],
  ARRAY['/assets/products/chunky-cinza-branco-dourado.png'],
  null,
  false,
  false,
  true,
  9,
  'published'
)
on conflict (slug) do nothing;
